### PR TITLE
plugin (locale): Error when usingDatePipe in Firefox 79 with timeStyle

### LINKED ISSUE #324: angular Transloco Date Pipe: can't set option timeStyle in Date.toLocaleDateString() in Firefox 79
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am getting an error in Firefox: Can't set option timeStyle.
Firefox 78 (yesterday was working)

```
      {{ value | translocoDate: { dateStyle: 'medium', timeStyle: 'short' } }}

```
original date String: 2019-02-01T07:30:23.00Z
In Firefox I debugged and saw that `localizeDate`  is called with the following options:
date: Date Sat Mar 21 2020 13:00:00 GMT+0100 (Mitteleuropäische Normalzeit)

```
locale: "de-DE"
options: {…}
dateStyle: "medium"
day: "2-digit"
hour: "2-digit"
​​minute: "2-digit"
​​month: "2-digit"
​​second: "2-digit"
​​timeStyle: "short"
​​year: "numeric"
```

Error log:

```
09:52:36.179 ERROR TypeError: can't set option timeStyle in Date.toLocaleDateString()
    localizeDate ngneat-transloco-locale.js:46
    transform ngneat-transloco-locale.js:834
    localizeDate ngneat-transloco-locale.js:922
    transform ngneat-transloco-locale.js:1158
    pipeBind2 Angular
    XXXComponent_ng_container_0_ng_template_37_Template xxxxx. component.html:62
    Angular 60
    RxJS 5
    Angular 18
    manageElementsStyle ng5-slider.js:1846
    ngAfterViewInit ng5-slider.js:1265
    Angular 24
    AppComponent_ng_container_0_Template app.component.html:33
    Angular 11
core.js:6241:19
    Angular 15
    RxJS 5
    Angular 18
    manageElementsStyle ng5-slider.js:1846
    ngAfterViewInit ng5-slider.js:1265
    Angular 24
    AppComponent_ng_container_0_Template app.component.html:33
    Angular 20
    RxJS 5
    Angular 17
    RxJS 22
```

## Expected behavior

No problems

## Minimal reproduction of the problem with instructions

In App Module:

export const globalFormatConfig: LocaleFormatOptions = {
  date: {
    dateStyle: 'medium',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    timeStyle: 'medium',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  }
};

imports: [
  TranslocoLocaleModule.init({
      localeConfig: {
        global: globalFormatConfig,
        localeBased: {
          'de-DE': globalFormatConfig,
          'en-US': globalFormatConfig
        }
      }
    }),
    TranslocoModule,
]

providers:[
  {
      provide: TRANSLOCO_CONFIG,
      useValue: {
        availableLangs: ['en-US', 'de-DE'],
        defaultLang: 'de-DE',
        fallbackLang: 'en-US',
        prodMode: environment.production,
      } as TranslocoConfig
    },
    TranslocoDatePipe,
    translocoLoader,
]

## Environment

<pre><code>

    "@ngneat/transloco": "^2.18.3",
    "@ngneat/transloco-locale": "^1.3.1",
  "@angular/common": "^9.1.12",
    "@angular/compiler": "^9.1.12",
    "@angular/core": "^9.1.12",
    "@angular/forms": "^9.1.12",
    "@angular/platform-browser": "^9.1.12",
    "@angular/platform-browser-dynamic": "^9.1.12",
    "@angular/router": "^9.1.12", 
    "@ionic/angular": "^5.3.0",
 
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 79
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.16.3
- Platform:  Windows 10 

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by Siedlerchr**
Hi, this is my first time doing a PR. 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features):
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Error in Firefox. No dates are displayed.

Issue Number: N/A
Fixes #324 

## What is the new behavior?
It works now again in Firefox.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information
See for Reference
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#JavaScript

### CODE REVIEW

**Comment by ahaeslich** [comment]
Is there a chance this fix will be released soon?

**Comment by itayod** [comment]
@ahaeslich we will try to get to it soon and release a new version as soon as it merged

**Comment by itayod** [comment]
@Siedlerchr could you please update the unit tests? please run `npm run test:locale`, some of the tests are failing

**Comment by Siedlerchr** [comment]
I fixed all tests, exept the last one, it seems to be some timezone issue (off by one hour)
`Expected 'Sep 12, 2019, 9:51:33 PM' to equal 'Sep 12, 2019, 10:51:33 PM'.`

**Comment by itayod** [comment]
@Siedlerchr LGTM

**Comment by Siedlerchr** [comment]
@itayod  Done!

**Comment by itayod** [comment]
thanks @Siedlerchr

**Pull request merged**
