### PR TITLE
fix: Change import of 'flat' library

### PR DESCRIPTION
**Pull request by jnain**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/ngneat/transloco/issues/587

## What is the new behavior?

My app builds with my modif but your lib transloco-schematics does not build anymore. And I don't really know why :( 

## Does this PR introduce a breaking change?

```
[ ] Yes 
[X] No (because one of the build step is broken)
```

### CODE REVIEW

**Comment by jnain** [comment]
Hello,

What can I do to make my PR going forward please?

Good day!

**Comment by angelnikolov** [comment]
Hello, I also stumbled upon this issue and seem to have resolved it the same way as @jnain does. Any chance this PR gets looked at? Thanks!

**Comment by shaharkazaz** [comment]
@jnain Thanks for the PR 
Can you please explain the changes you made here?

**Comment by jnain** [comment]
@shaharkazaz 
Hello !

I changed the Flat library import because it was messing with the ESM compiler.
Then ; to allow the compiler to accept this kind of import "import _flatten from 'flat';", I added the "allowSyntheticDefaultImports": true, in tsconfig file.

Then I removed the rootDir because it seems it is not necessary as I could build the project without it...

I don't really know if this fix for ESM Compiler still allows the OLD compiled version (without ESM) to work correctly.

Have a great day,
Jonathan.

**Comment by shaharkazaz** [comment]
@jnain I think that actual solution would be the release of flat@6.0.0 which was converted to ESM. 
If it doesn't move in that direction soon I'll see how we can push this forward and make sure it's not braking anything.

**Comment by shaharkazaz** [comment]
Will update to [flat@6](https://github.com/hughsk/flat/issues/156) once it's released.

**Comment by vojtesaak** [comment]
> Will update to [flat@6](https://github.com/hughsk/flat/issues/156) once it's released.

It has been released today 🚀

**Comment by shaharkazaz** [comment]
@vojtesaak yes I know :)
I've tried upgrading but it broke some tests, I'll need some time to see what's up

**Pull request closed without merging**
