### PR TITLE
chore: 🤖 upgrade to angular v16

### PR DESCRIPTION
**Pull request by chimurai**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Update Angular to v16
Update nx to v15.9.2

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

### CODE REVIEW

**Comment by chimurai** [comment]
fixed merge conflicts in #642 and upgraded to Angular v16

Manually checked `npm run start`

And I ran these tests locally:

```shell
npm run ci:test -- --skipNxCache
npm run ci:build -- --skipNxCache
npm run ci:lint -- --skipNxCache
npm run ci:e2e -- --skipNxCache
npm run lint
npm run e2e
```

**Comment by chimurai** [comment]
Think the peerDependencies need to be update as well?

```diff
-   "@angular/core": ">=13.0.0", 
+   "@angular/core": ">=16.0.0", 
```

https://github.com/ngneat/transloco/blob/9b3af32d2147c6d5c15aa101c7a2c497c2789128/libs/transloco-locale/package.json#L27-L29

**Comment by alexfriesen** [comment]
I there a good reason to update nx to version 15 and not the latest version?

**Comment by chimurai** [comment]
@alexfriesen
The original PR https://github.com/ngneat/transloco/pull/642 was opened on April 2nd to upgrade to NG15.
At that time NX 15 was the latest.

Meanwhile NG16 got released, so this PR was opened to solve merge conflicts and upgraded to NG16.

Didn't update NX to latest to keep the scope small.

And to be honest; I can't keep spending time to keep this PR up-to-date...

**Comment by shaharkazaz** [comment]
@chimurai First of all, thank you for the time spent on the and the previous PR.
It's not unnoticed.
As a single maintainer to a big repo such as this and other projects it's hard to get to things considering the fact that I also have to work and have a life with my family 😂 

I'll do my best to push this forward ASAP.
Not sure if you noticed but I'm trying to push thing forward in the last couple of weeks, but TBH it's hard.

Thanks again for the PR :)

**Review by shaharkazaz — APPROVED** [review]

**Comment by anikets43** [comment]
I appreciate @chimurai for handling the PR and @shaharkazaz for successfully merging it. I'm excited about getting it published on npm and trying out the latest Angular version.

**Comment by chimurai** [comment]
Totally recognizable and relatable @shaharkazaz;
All of our time is limited and valuable.

Really appreciate the work and care you've put into this project. 🙏

Hopefully community contributions help out to relief the maintenance burden a bit. (OSS ftw 😊)

**Comment by shaharkazaz** [comment]
Thanks guys.
There is a bit more work do be done there before releasing the new version (some deprecations and reactors, docs etc) but I'm aiming for this week 💪

**Comment by shaharkazaz** [comment]
@anikets43 As soon as I have time to complete the transition. I'm about half way there.

**Pull request merged**
