### PR TITLE
feat: lazy load

### PR DESCRIPTION
**Pull request by NetanelBasal**
@itayod @shaharkazaz tell me what you think.

### CODE REVIEW

**Comment by itayod** [comment]
LGTM, I especially liked the template.
few nits:
* maybe we can create some token that will pass a global template, instead redeclare it every time the user uses the directive. 
* I am not sure that cache will work for lazy loaded features and will load the translation again.

**Comment by NetanelBasal** [comment]
- That's a good idea. They can do it per lazy module.
- Why not? it's a singleton service.

**Comment by itayod** [comment]
> * That's a good idea. They can do it per lazy module.
> * Why not? it's a singleton service.

because the cache currently only get lang as key, I think we will need to consider also the scope, or am I wrong?

**Comment by NetanelBasal** [comment]
No, the cache takes a string.

**Pull request merged**
