### PR TITLE
fix: directive TranslocoDirective doesn't work on Universal SSR

### PR DESCRIPTION
**Pull request by pascalmann**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The directive TranslocoDirective does not inject translation in Universal SSR mode.

## What is the new behavior?
A little function has been added (from ngx-translate) to update the node text.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by pascalmann** [comment]
Sorry for my commit message...

**Comment by itayod** [comment]
@pascalmann looking at your pr there are few things that missing:
1. please add a type to the `node`
2. what is `node.data` could you point me to some documentation that explains it?

**Comment by shaharkazaz** [comment]
@pascalmann have you seen @itayod comments? 🙂

**Comment by shaharkazaz** [comment]
@pascalmann Do you think you will have the time to address @itayod comments?

**Comment by shaharkazaz** [comment]
Fixed in v3.1.1

**Pull request closed without merging**
