### PR TITLE
feat: 🎸 message-format cache compiled messages

### PR DESCRIPTION
**Pull request by k3nsei**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Message format compile is always used.

Issue Number: #358

## What is the new behavior?

Message format use compile only once per message.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information
none

### CODE REVIEW

**Comment by itayod** [comment]
Hi @k3nsei LGTM, but I don't think we want that as default behavior, so let's add it as an option in the plugin's configuration and make it "false" by default.

**Comment by shaharkazaz** [comment]
@k3nsei Hey! will you have the time to do the change requested by @itayod so we continue with this PR? 🙂

**Comment by k3nsei** [comment]
@shaharkazaz yes I will do that.

**Comment by itayod** [comment]
Hi @k3nsei, thanks for the update.

- can you add this optimization to the plugin's config and make it `false` by default (as I wrote above).
- if you may, you can add it to the documentation.
- please don't force push it makes it hard to track the changes :)

Thanks!

**Comment by itayod** [comment]
@k3nsei Hey!
I really want to push this forward 🙏 (and add you as a contributor! 🥳 )

These are the fixes needed:
* Make this optimization configurable as part of the config passed to the module with the default of `false`( we will make it `true` by default in the next major version, but we don't want any side effects now).
* Update the docs accordingly.
* Add short tests making sure it's working as expected.

We're here if you need assistance. Let's merge this thing. 💪

**Comment by k3nsei** [comment]
@itayod You can pick it up. I can't find free time to move it forward.

**Comment by itayod** [comment]
> @itayod You can pick it up. I can't find free time to move it forward.

No rush, feel free to continue work this when you can.

**Comment by shaharkazaz** [comment]
Added in v3

**Comment by zhienbaevsa** [comment]
@shaharkazaz Hi! What is the fate of this feature request?

**Pull request closed without merging**
