### PR TITLE
🐛 fix img path

### PR DESCRIPTION
**Pull request by lukechi1219**
fix ../../img/installation.gif

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by shaharkazaz** [comment]
@lukechi1219 Seems like the gif on the [installation docs page](https://ngneat.github.io/transloco/docs/installation) is working as expected.
What's the issue here?

**Comment by shaharkazaz** [comment]
@lukechi1219 I think I had a cached version of the docs. Thanks.

**Review by shaharkazaz — APPROVED** [review]

**Comment by shaharkazaz** [comment]
@lukechi1219 Can you please also fix the gif path of the `scope-lib-extractor`? and please commit your changes using the `commit` command and force push to this branch.

**Comment by lukechi1219** [comment]
> @lukechi1219 I think I had a cached version of the docs. Thanks.

hi, sorry for bothering you with such a small issue... btw I think it's not about cache. It seems related to react handle base URL of the installation.gif image.

when I first go to URL https://ngneat.github.io/transloco/docs/config-options , then click "Getting Started > Installation"

the image show normally

but if I refresh the page at https://ngneat.github.io/transloco/docs/installation

the image is broken.

**Comment by shaharkazaz** [comment]
@lukechi1219 That's why I saw it working for the first time, nice catch.
Would you like to look into it? might be related to docusaurus

**Comment by lukechi1219** [comment]
@shaharkazaz Well, I'm not familiar with docusaurus, but I can look into it in my free time.

**Comment by lukechi1219** [comment]
@shaharkazaz I've fixed the image path with @docusaurus/useBaseUrl . I run and check at my local machine and it looks good. The image will still show after I refresh the page.

**Comment by shaharkazaz** [comment]
@lukechi1219 Nice work! Would you please commit your changes using the `commit` command and force push to this branch?

**Comment by lukechi1219** [comment]
> @lukechi1219 Nice work! Would you please commit your changes using the `commit` command and force push to this branch?

Hi @shaharkazaz , sorry I'm not sure what you mean... it's the first time in my life issue a pull request...

**Comment by shaharkazaz** [comment]
@lukechi1219 no worries, I'll explain.
We are using a commit convention to automate the package versioning, and currently, your commit isn't matching that convention.

Here are the steps you need:
* Do a **soft** reset to your changes.
* Add the changes to git via `git add` 
* Run `npm run commit`.
* Force push to remote.

The commit command will prompt a series of questions (you should choose 'docs' for type) that will build the formatted commit message for you, and once done, it will commit the changes.

Because you already have a remote branch with commits, you will need to force push your fresh commit to make it the new HEAD.

Alternatively, since these are minor changes, you can create a new branch, redo the changes, commit them via the command and open a new PR.

Hope this helps.

**Comment by lukechi1219** [comment]
@shaharkazaz  Thanks! Now I know "commit command" refers to "npm run commit". I will try it later tonight.

**Comment by lukechi1219** [comment]
> @shaharkazaz Thanks! Now I know "commit command" refers to "npm run commit". I will try it later tonight.

@shaharkazaz , I suggest adding this step "npm run commit" in CONTRIBUTING.md , but my English is not very fluent... so just leave it to you. lol

**Review by shaharkazaz — APPROVED** [review]

**Comment by shaharkazaz** [comment]
@lukechi1219 I'll need you to re-commit and skip the braking change question (just press Enter) since giving it a value is considered that this commit has a breaking change 🙂

**Comment by lukechi1219** [comment]
> @lukechi1219 I'll need you to re-commit and skip the braking change question (just press Enter) since giving it a value is considered that this commit has a breaking change 🙂

It's odd executing "npm run commit" on my windows nb... the commit message "longer description of the change" will disappear... I'll re-commit tonight with my mac book. :(

**Comment by lukechi1219** [comment]
New commit force pushed, please kindly review.

**Pull request merged**
