### PR TITLE
fix(migrate): 🐛 improve "translate" pipe regex

### PR DESCRIPTION
**Pull request by hakimio**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

`translate` pipe regex doesn't match some pipe usages.

Issue Number: #701

## What is the new behavior?

`translate` pipe regex matches more different kind of pipe usages.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by shaharkazaz — COMMENTED** [review]
Thanks for the PR! seems clearer now.

From my experience, the standalone test cases are not sufficient to cover an actual run.
The main issue I had when working with these regexes was that it would include parts that we didn't want to include.
Can you add a text of a "full template" just to make sure the line breaks, white spaces or whatever doesn't break the behavior? I have several examples we can just copy paste and expect the pipes and directives to be updated

**Comment by hakimio** [comment]
Can you share the example code you want to test?

**Comment by shaharkazaz** [comment]
@hakimio Yes of course. [Here](https://github.com/ngneat/transloco-keys-manager/tree/master/__tests__) you can find several examples of templates containing pipes, directives, etc.
It would be a good idea to copy these tests and make sure they are migrated correctly and if we have cases that are not supported it's good to be aware of them and we can add them, to the known limitations.

**Comment by hakimio** [comment]
How can I find all the `dontTake` cases in the `pipe` directory?
https://github.com/ngneat/transloco-keys-manager/tree/master/__tests__/pipe

**Comment by hakimio** [comment]
I guess, all the cases, where the key is non-numeric, are considered invalid.

**Comment by hakimio** [comment]
I have added the HTML template test.

There are a couple of cases which are not handled correctly, but I don't think they matter as they are quite rare.

1. It doesn't handle the case when there are newlines inside `{{ ... }}`:
```html
<div>
  {{ (condition ? '40' :

  '41') | translate: { name: "ccc"} }}
</div>
```
2. It doesn't validate the html template. So, it will just do the replacement in the following cases even there are errors in the template:
```html
<span>{{ 'not' + 4 | translate }}</span>
<span>{{ 'numer' ++ 4 | translate }}</span>
<span>{{ var + 'not'  | translate }}</span>
```

**Review by shaharkazaz — APPROVED** [review]
Awesome job 🚀

**Comment by shaharkazaz** [comment]
@hakimio Seems like the lint is failing, can you run a lint fix?

**Comment by hakimio** [comment]
It's in a file I haven't touched: https://github.com/ngneat/transloco/actions/runs/6223666982/job/16901003211?pr=702#step:4:240
```
Linting "transloco-optimize"...

/home/runner/work/transloco/transloco/libs/transloco-optimize/src/lib/transloco-optimize.ts
Warning:   7:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```

Anyway, I'll take a look tomorrow.

**Comment by hakimio** [comment]
Ok, the lint error is in the import order.
I'll fix it and push tomorrow.

**Comment by shaharkazaz** [comment]
Please pull master as well 🙂

**Comment by hakimio** [comment]
Should be good now.

**Comment by hakimio** [comment]
Just merge the PR as a single commit with whatever commit message you want. I am not going to change all the commit messages.

**Comment by shaharkazaz** [comment]
@hakimio You have commits that aren't following the guidelines, can you please fix them so we can merge? 🙂 
The last three commits before the master merge seem to be off the standards.

**Comment by hakimio** [comment]
Just merge this as a single commit with message `fix(migrate): 🐛 improve "translate" pipe regex`.

**Pull request merged**
