### PR TITLE
fix(dependencies): update fs-extra and glob dependencies

### PR DESCRIPTION
**Pull request by PeterHewat**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #630

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by shaharkazaz** [comment]
Can you please do the same for glob?

**Comment by shaharkazaz** [comment]
Please use the commit command to follow the convention.

Force push a single commit that was generated via the command

**Comment by PeterHewat** [comment]
ok, will do.

**Comment by PeterHewat** [comment]
There, hope this is how it should be done now :-)

**Comment by PeterHewat** [comment]
@shaharkazaz is there anything else I need to do to get this PR through ?

**Pull request merged**
