### PR TITLE
feat: access to active language and up-to-date config in MissingHandler

### LINKED ISSUE #164: Access TranslocoService in custom TranslocoMissingHandler
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, the handle method receives the missing key and the config. The config object passed to `handle` is not an up-to-date representation of the current settings e.g. calling `setAvailableLangs` does not update `config.availableLangs`.

## Expected behavior
The handle method should be given access to important up-to-date properties such as active language. Perhaps the TranslationService itself can passed to the handle method. This might be a circular reference so alternatively an info object could be passed.

## What is the motivation / use case for changing the behavior?
I would like to access the active language to properly deal with and log missing keys.

### PR DESCRIPTION
**Pull request by MatthiasKunnen**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
- There is no access to `activeLang` in the missing key handler. 
- `defaultLang` and `availableLangs` could be out-of-date

Issue Number: Closes #164

## What is the new behavior?
- Include `activeLang` in the info object passed to `MissingHandler.handle()`
- Pass up-to-date versions of aforementioned properties

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```
**Questions**  
I searched for a way to update the docs at <https://netbasal.gitbook.io/transloco/hack-the-library/transloco-missing-handler> but couldn't find anything related in the repo. Have I missed something?

I saw you have a contributors file, am I supposed to add myself to it? And if so, with what _contributions_ (code, ideas)?

I could not find any info regarding this in CONTRIBUTING.md file.

### CODE REVIEW

**Comment by shaharkazaz** [comment]
@MatthiasKunnen Thanks for the PR, I saw you are creating a new object for each missing handler call which is something we would like to avoid.
I think a better solution would be to clone the original config and keep it up to date, what do you think?

**Comment by MatthiasKunnen** [comment]
You would prefer adding a `missingInfo` object to class level and keeping that object up-to-date? And `config` would not be kept up-to-date?

**Comment by shaharkazaz** [comment]
I talked with @NetanelBasal about it, and we want to avoid changing the original object since we don't want any side effects.
We will go with the code you suggested, for now, please change the Interface to `TranslocoMissingHandlerData`.

**Comment by MatthiasKunnen** [comment]
Done

**Comment by MatthiasKunnen** [comment]
Can you tell me anything about the two questions in the PR's description?

**Comment by MatthiasKunnen** [comment]
I've also logged the language in the default missing handler, If you don't want that change I'll remove it.

**Comment by shaharkazaz** [comment]
Please rename `getMissingInfo ` to  `getMissingHandlerData` and remove the log, seems redundant, people know what their active language is.

As for your questions: 
1. I will update the docs in this case since it's a small change but in general, we give permissions to edit the docs if needed.
2. I will add you as a contributor.

**Comment by MatthiasKunnen** [comment]
Done

**Pull request merged**
